# Generated by Django 2.0.4 on 2018-04-13 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_R_and_L', '0002_auto_20180413_1614'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='userID',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='user',
            name='userID',
            field=models.IntegerField(default=100, primary_key=True, serialize=False),
        ),
    ]
