# Generated by Django 2.0.4 on 2018-04-13 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_R_and_L', '0003_auto_20180413_2120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='id',
        ),
        migrations.AddField(
            model_name='comment',
            name='commentID',
            field=models.IntegerField(default=100, primary_key=True, serialize=False),
        ),
    ]
