# Generated by Django 2.0.4 on 2018-04-24 05:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_R_and_L', '0006_auto_20180413_2306'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('blogID', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=40)),
                ('content', models.CharField(max_length=5000)),
                ('external_file_name', models.CharField(max_length=100)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_R_and_L.User')),
            ],
        ),
    ]
