# Generated by Django 2.0.4 on 2018-04-27 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_R_and_L', '0007_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='agree',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='blog',
            name='oppose',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='blog',
            name='publish_time',
            field=models.DateField(auto_now=True),
        ),
    ]
