# Generated by Django 2.0.4 on 2018-04-27 15:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app_R_and_L', '0008_auto_20180427_2254'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='userImageName',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
